
export const ADD_BOOKING_DETAILS_REQUEST = "ADD_BOOKING_DETAILS_REQUEST";
export const ADD_BOOKING_DETAILS_SUCCESS = "ADD_BOOKING_DETAILS_SUCCESS";
export const ADD_BOOKING_DETAILS_FAILURE = "ADD_BOOKING_DETAILS_FAILURE";

export const GET_BOOKING_DETAILS_REQUEST = "GET_BOOKING_DETAILS_REQUEST";
export const GET_BOOKING_DETAILS_SUCCESS = "GET_BOOKING_DETAILS_SUCCESS";
export const GET_BOOKING_DETAILS_FAILURE = "GET_BOOKING_DETAILS_FAILURE";

// Additional Booking Actions (if needed in the future)
export const ADD_SEATS_TO_BOOKING_REQUEST = "ADD_SEATS_TO_BOOKING_REQUEST";
export const ADD_SEATS_TO_BOOKING_SUCCESS = "ADD_SEATS_TO_BOOKING_SUCCESS";
export const ADD_SEATS_TO_BOOKING_FAILURE = "ADD_SEATS_TO_BOOKING_FAILURE";

export const CHECKOUT_BOOKING_REQUEST = "CHECKOUT_BOOKING_REQUEST";
export const CHECKOUT_BOOKING_SUCCESS = "CHECKOUT_BOOKING_SUCCESS";
export const CHECKOUT_BOOKING_FAILURE = "CHECKOUT_BOOKING_FAILURE";

export const ADD_DONATION_REQUEST = "ADD_DONATION_REQUEST";
export const ADD_DONATION_SUCCESS = "ADD_DONATION_SUCCESS";
export const ADD_DONATION_FAILURE = "ADD_DONATION_FAILURE";
